[package]
name = "nft-metadata-crawler-parser"
description = "NFT Metadata Crawler Parser service."
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }
diesel = { workspace = true }
futures = { workspace = true }
google-cloud-auth = { workspace = true }
google-cloud-googleapis = { workspace = true }
hyper = { workspace = true }
image = { workspace = true }
nft-metadata-crawler-utils = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
